kmd_municipality:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"
      authenticator: "{{ env_var('SNOWFLAKE_AUTHENTICATOR', 'snowflake') }}"
      role: SYSADMIN
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: KMD_WH
      schema: RAW
      threads: 4
