kmd_municipality:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ""
      user: ""
      database: "{{ env_var('DBT_DATABASE', 'ESBJERG_DB') }}"
      warehouse: KMD_WH
      role: SYSADMIN
      schema: ANALYTICS
