name: 'kmd_schools'
version: '1.0.0'
config-version: 2

profile: 'kmd_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  start_date: '2024-01-01'
  end_date: '2024-12-31'

seeds:
  kmd_schools:
    seed_municipalities:
      +schema: staging

models:
  kmd_schools:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']
    
    intermediate:
      +materialized: ephemeral
      +tags: ['intermediate']
    
    marts:
      core:
        +materialized: table
        +schema: gold
        +tags: ['marts', 'core']
      
      analytics:
        +materialized: table
        +schema: gold
        +tags: ['marts', 'analytics']
