kmd_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"
      authenticator: "{{ env_var('SNOWFLAKE_AUTHENTICATOR', 'snowflake') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'SYSADMIN') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'KMD_SCHOOLS') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'KMD_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'STAGING') }}"
      threads: 4
