-- ============================================================================
-- KMD WORKSHOP - STEP 4: SECURITY (Roles, RLS, Dynamic Masking)
-- ============================================================================
-- Creates roles, row-level security, and dynamic data masking policies
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE KMD_WH;

-- ============================================================================
-- ROLES (Municipality-specific analysts + admin)
-- ============================================================================

CREATE ROLE IF NOT EXISTS COPENHAGEN_ANALYST;
CREATE ROLE IF NOT EXISTS AARHUS_ANALYST;
CREATE ROLE IF NOT EXISTS ODENSE_ANALYST;
CREATE ROLE IF NOT EXISTS AALBORG_ANALYST;
CREATE ROLE IF NOT EXISTS ESBJERG_ANALYST;
CREATE ROLE IF NOT EXISTS KMD_DATA_ADMIN;

-- Grant database/schema access to all analyst roles
GRANT USAGE ON DATABASE KMD_SCHOOLS TO ROLE COPENHAGEN_ANALYST;
GRANT USAGE ON DATABASE KMD_SCHOOLS TO ROLE AARHUS_ANALYST;
GRANT USAGE ON DATABASE KMD_SCHOOLS TO ROLE ODENSE_ANALYST;
GRANT USAGE ON DATABASE KMD_SCHOOLS TO ROLE AALBORG_ANALYST;
GRANT USAGE ON DATABASE KMD_SCHOOLS TO ROLE ESBJERG_ANALYST;
GRANT USAGE ON DATABASE KMD_SCHOOLS TO ROLE KMD_DATA_ADMIN;

GRANT USAGE ON DATABASE KMD_STAGING TO ROLE COPENHAGEN_ANALYST;
GRANT USAGE ON DATABASE KMD_STAGING TO ROLE AARHUS_ANALYST;
GRANT USAGE ON DATABASE KMD_STAGING TO ROLE ODENSE_ANALYST;
GRANT USAGE ON DATABASE KMD_STAGING TO ROLE AALBORG_ANALYST;
GRANT USAGE ON DATABASE KMD_STAGING TO ROLE ESBJERG_ANALYST;
GRANT USAGE ON DATABASE KMD_STAGING TO ROLE KMD_DATA_ADMIN;

GRANT USAGE ON SCHEMA KMD_STAGING.RAW TO ROLE COPENHAGEN_ANALYST;
GRANT USAGE ON SCHEMA KMD_STAGING.RAW TO ROLE AARHUS_ANALYST;
GRANT USAGE ON SCHEMA KMD_STAGING.RAW TO ROLE ODENSE_ANALYST;
GRANT USAGE ON SCHEMA KMD_STAGING.RAW TO ROLE AALBORG_ANALYST;
GRANT USAGE ON SCHEMA KMD_STAGING.RAW TO ROLE ESBJERG_ANALYST;
GRANT USAGE ON SCHEMA KMD_STAGING.RAW TO ROLE KMD_DATA_ADMIN;

GRANT SELECT ON ALL TABLES IN SCHEMA KMD_STAGING.RAW TO ROLE COPENHAGEN_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA KMD_STAGING.RAW TO ROLE AARHUS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA KMD_STAGING.RAW TO ROLE ODENSE_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA KMD_STAGING.RAW TO ROLE AALBORG_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA KMD_STAGING.RAW TO ROLE ESBJERG_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA KMD_STAGING.RAW TO ROLE KMD_DATA_ADMIN;

-- Grant warehouse access
GRANT USAGE ON WAREHOUSE KMD_WH TO ROLE COPENHAGEN_ANALYST;
GRANT USAGE ON WAREHOUSE KMD_WH TO ROLE AARHUS_ANALYST;
GRANT USAGE ON WAREHOUSE KMD_WH TO ROLE ODENSE_ANALYST;
GRANT USAGE ON WAREHOUSE KMD_WH TO ROLE AALBORG_ANALYST;
GRANT USAGE ON WAREHOUSE KMD_WH TO ROLE ESBJERG_ANALYST;
GRANT USAGE ON WAREHOUSE KMD_WH TO ROLE KMD_DATA_ADMIN;

-- ============================================================================
-- ROW-LEVEL SECURITY (RLS)
-- Each analyst role can only see their municipality's data
-- ============================================================================

USE DATABASE KMD_SCHOOLS;
USE SCHEMA SHARED;

CREATE OR REPLACE ROW ACCESS POLICY MUNICIPALITY_RLS AS (municipality_code NUMBER) RETURNS BOOLEAN ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('SYSADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('KMD_DATA_ADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('COPENHAGEN_ANALYST') AND municipality_code = 101 THEN TRUE
        WHEN IS_ROLE_IN_SESSION('AARHUS_ANALYST') AND municipality_code = 751 THEN TRUE
        WHEN IS_ROLE_IN_SESSION('ODENSE_ANALYST') AND municipality_code = 461 THEN TRUE
        WHEN IS_ROLE_IN_SESSION('AALBORG_ANALYST') AND municipality_code = 851 THEN TRUE
        WHEN IS_ROLE_IN_SESSION('ESBJERG_ANALYST') AND municipality_code = 561 THEN TRUE
        ELSE FALSE
    END;

-- Apply RLS to RAW tables
ALTER TABLE KMD_STAGING.RAW.SCHOOLS_RAW ADD ROW ACCESS POLICY KMD_SCHOOLS.SHARED.MUNICIPALITY_RLS ON (municipality_code);
ALTER TABLE KMD_STAGING.RAW.TEACHERS_RAW ADD ROW ACCESS POLICY KMD_SCHOOLS.SHARED.MUNICIPALITY_RLS ON (municipality_code);
ALTER TABLE KMD_STAGING.RAW.STUDENTS_RAW ADD ROW ACCESS POLICY KMD_SCHOOLS.SHARED.MUNICIPALITY_RLS ON (municipality_code);
ALTER TABLE KMD_STAGING.RAW.CLASSES_RAW ADD ROW ACCESS POLICY KMD_SCHOOLS.SHARED.MUNICIPALITY_RLS ON (municipality_code);

-- ============================================================================
-- DYNAMIC DATA MASKING POLICIES
-- ============================================================================

-- CPR Number Masking (Danish SSN - format: DDMMYY-XXXX)
CREATE OR REPLACE MASKING POLICY CPR_MASK AS (val VARCHAR) RETURNS VARCHAR ->
    CASE 
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('SYSADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('KMD_DATA_ADMIN') THEN val
        ELSE CONCAT(LEFT(val, 6), '-XXXX')
    END;

-- Email Masking
CREATE OR REPLACE MASKING POLICY EMAIL_MASK AS (val VARCHAR) RETURNS VARCHAR ->
    CASE 
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('SYSADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('KMD_DATA_ADMIN') THEN val
        ELSE CONCAT('***@', SPLIT_PART(val, '@', 2))
    END;

-- Phone Masking
CREATE OR REPLACE MASKING POLICY PHONE_MASK AS (val VARCHAR) RETURNS VARCHAR ->
    CASE 
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('SYSADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('KMD_DATA_ADMIN') THEN val
        ELSE CONCAT(LEFT(val, 7), '** ** **')
    END;

-- Apply masking policies to columns
ALTER TABLE KMD_STAGING.RAW.STUDENTS_RAW MODIFY COLUMN cpr_number SET MASKING POLICY CPR_MASK;
ALTER TABLE KMD_STAGING.RAW.STUDENTS_RAW MODIFY COLUMN guardian_email SET MASKING POLICY EMAIL_MASK;
ALTER TABLE KMD_STAGING.RAW.STUDENTS_RAW MODIFY COLUMN guardian_phone SET MASKING POLICY PHONE_MASK;

ALTER TABLE KMD_STAGING.RAW.TEACHERS_RAW MODIFY COLUMN cpr_number SET MASKING POLICY CPR_MASK;
ALTER TABLE KMD_STAGING.RAW.TEACHERS_RAW MODIFY COLUMN email SET MASKING POLICY EMAIL_MASK;
ALTER TABLE KMD_STAGING.RAW.TEACHERS_RAW MODIFY COLUMN phone SET MASKING POLICY PHONE_MASK;

-- ============================================================================
-- VERIFY SECURITY SETUP
-- ============================================================================

-- List policies
SHOW MASKING POLICIES IN SCHEMA KMD_SCHOOLS.SHARED;
SHOW ROW ACCESS POLICIES IN SCHEMA KMD_SCHOOLS.SHARED;

-- Test RLS (run as COPENHAGEN_ANALYST with USE SECONDARY ROLES NONE)
-- Should only see municipality_code = 101
